id: AB28C6A01
base_file: f5ADA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:00:54.230930
  last_modified_at: 2022-06-05 20:00:54.230934
