id: AB28C6A01
base_file: f2521.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:00:54.213585
  last_modified_at: 2022-06-05 20:00:54.213594
