id: AB28C6A01
base_file: f25F8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:00:54.218844
  last_modified_at: 2022-06-05 20:00:54.218851
