id: AB28C6A01
base_file: fE488.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:00:54.238183
  last_modified_at: 2022-06-05 20:00:54.238186
